---
output: pdf_document
header-includes: 
  - \usepackage[utf8]{inputenc}
  - \usepackage{graphicx}
  - \usepackage{caption}
  - \usepackage[margin=1in]{geometry}
  - \usepackage{amsmath,amssymb}
  - \usepackage{multicol}
  - \usepackage{array}
  - \usepackage{tabulary}
  - \usepackage{tikz}
  - \usetikzlibrary{arrows,calc}
  - \usepackage{relsize}
  - \usetikzlibrary{decorations.pathreplacing}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newcommand{\class}{EC 313, Summer 2019}
\newcommand{\term}{Xiang LI (GE)}
\newcommand{\examnum}{Chapter 8 - Practice}

\noindent
\begin{tabular*}{\textwidth}{l @{\extracolsep{\fill}} r @{\extracolsep{6pt}} l}
\textbf{\class} & \textbf{Name: } & \makebox[2in]{\hrulefill}\\
\textbf{\term} &&\\
\textbf{\examnum} & \textbf{UO ID: } & \makebox[2in]{\hrulefill}\\
\end{tabular*}
\rule[2ex]{\textwidth}{2pt}




\textbf{QUESTION 1: TRUE, FALSE}

(1) The original Phillips curve relation has proven to be very stable across countries and over time.

\vspace{.3in}

(2) Expected inflation always equals actual inflation.

\vspace{.3in}

(3) If people assume that inflation will be the same as last year’s inflation, the Phillips curve relation will be a relation between the level in the inflation rate and the unemployment rate.

\vspace{.3in}

(4) The natural rate of unemployment is constant over time within a county

\vspace{.3in}

(5) Deflation means that the rate of inflation is negative.

\vspace{.3in}


\vspace{.5in}
\textbf{QUESTION 2}

This question asks about the natural rate of unemployment.

(1) The Phillips curve is $\pi_t = \pi_t^e + (m+z) - \alpha z$. Rewrite this relation as a relation between the deviation of the unemployment rate from the natural rate, inflation, and expected inflation.

\vspace{1in}

(2)  In the previous chapter, we derived the natural rate of unemployment. What condition on the price level and the expected price level was imposed in that derivation? How does it relate to the condition imposed in part (1)?

\vspace{.7in}

(3) How does the natural rate of unemployment vary with the markup?

\vspace{.7in}

(4)  How does the natural rate of unemployment vary with the catchall term z ?

\vspace{.7in}


\newpage
\vspace{.5in}
\textbf{QUESTION 3} 

Suppose that the Phillips curve is given by $\pi_t = \pi^e_t + 0.1 - 2 u_t$, and expected inflation is given by $\pi^e_t = (1-\theta) \bar{\pi}+\theta \pi_{t-1}$, and suppose that $\theta$ is initially equal to 0 and $\bar{\pi}$ is given and does not change. It could be zero or any positive value. Suppose that the rate of unemployment is initially equal to the natural rate. In year t, the authorities decide to bring the unemployment rate down to 3% and hold it there forever


(1) Determine the rate of inflation in periods t+1, t+2, t+3, t+4, t+5. 

\vspace{4in}


(2) Do you believe the answer given in (1)? Why or why not? (Hint: Think about how people are more likely to form expectations of inflation.) 

\vspace{1in}

Now suppose that in year t+6, $\theta$ increases from 0 to 1. Suppose that the government is still determined to keep the unemployment rate at 3% forever.

(3) Why might $\theta$ increase in this way?

\vspace{1in}

\newpage
(4) What will the inflation rate be in years t+6, t+7, and t+8?

\vspace{2in}


(5) What happens to inflation when $\theta=1$ and unemployment is kept below the natural rate of unemployment?

\vspace{1in}

(6) What happens to inflation when $\theta=1$ and unemployment is kept at the natural rate of unemployment?

\vspace{1in}



\vspace{.5in}
\textbf{QUESTION 4} 

The text proposes the following model of expected inflation: $\pi^e_t = (1-\theta) \bar{\pi}+\theta \pi_{t-1}$.

(1) Describe the process of the formation of expected inflation when $\theta = 0$.

\vspace{1in}
(2) Describe the process of the formation of expected inflation when $\theta = 1$.

\vspace{1in}

\newpage
\vspace{.5in}
\textbf{QUESTION 5} 

What are the two key factors that lead to variations in the Phillips curve over time and across countries?

\vspace{2in}


\vspace{.5in}
\textbf{QUESTION 6} 

The theoretical Phillips Curve is given by $\pi_t = \pi^e_t + (m+z)-\alpha u_t$. This tells us that when people expect inflation to be high, actual inflation is also high. Appealing to the labor market, explain why this is the case.

\vspace{2in}


\vspace{.5in}
\textbf{QUESTION 7} 

We can write the Phillips Curve as $\pi_t - \pi^e_t = -\alpha (u_t-u_n)$. This tells us that when the unemployment rate is higher than the natural unemployment rate, inflation is lower than its expectation. Appealing to the labor market, explain why this is the case.

\vspace{2in}


\vspace{.5in}
\textbf{QUESTION 8} 

Explain the different implications that the Phillips curve has for the relationship between inflation and unemployment when economic agents have static inflation expectations as opposed to adaptive inflation expectations.

\vspace{2in}






